---
title: "Stock Table"
author: "Robert Woody"
date: "10/23/2020"
output: 
  html_document:
    css: stock.css
---

```{r setup, include=FALSE}
library(reactable)
library(readr)
library(dplyr)
library(tidyr)
library(shiny)
library(crosstalk)
library(ggplot2)
library(lubridate)
library(sparkline)
library(stringr)
knitr::opts_chunk$set(echo = TRUE)

```

## Stock Data

```{r cars}
stocks <- read_csv("./data/stocks.csv") 
stocks <- stocks %>% mutate_if(is.numeric, ~round(.x,2))
preview <- stocks %>% group_by(ticker) %>% arrange(desc(date)) %>% group_modify(~head(.x,80))
reactable(preview %>% mutate_if(is.numeric, ~round(.x,5)))
```


```{r}
# Verify the data is pretty clean
min(stocks$date)
stocks %>% 
  subset(date >= "2013-08-24") %>% 
  group_by(ticker) %>% 
  summarise(dates = length(unique(date)),
            first = min(date))
# Pay Pal is the exception, has less days.# 793

selected_stocks <- read_csv("./data/top_50.csv") %>% mutate(Symbol = str_trim(Symbol))

stock_names <- sapply(selected_stocks[['Name']],
                      function(x,y){y}, 
                      y = selected_stocks$Symbol,simplify = FALSE)
stock_names <- selected_stocks$Name
names(stock_names) <- selected_stocks$Symbol
stock_names
purrr::pluck(stock_names,"AAPL")
```

```{r}
preview
```
```{r}
min_date <- max(stocks$date) %m+% years(-6)
stocks <- stocks %>% subset(date >= min_date)
lag_levels <- c("1 Week","1 Month","3 Months","6 Months","1 Year","2 Years","5 Years")

framework <- 
  stocks %>% 
  ungroup() %>%
  mutate(lag = factor(rep("1 Month", nrow(.)), levels = lag_levels))%>%
  expand(ticker,lag) 

stocks_l <- framework %>% left_join(stocks, by = "ticker")
```


```{r}

convert_lag <- function(gdf,end_date){
  lag <- str_to_lower(unique(gdf$lag)[1])
  if (str_detect(lag,"week")){
    start_date <- end_date %m+% weeks(-1 * str_split(lag, " ")[[1]][1] %>% as.integer())
  }else if(str_detect(lag,"month")){
    start_date <- end_date %m+% months(-1 * str_split(lag, " ")[[1]][1] %>% as.integer())
  }
  else if(str_detect(lag,"year")){
    start_date <- end_date %m+% years(-1 * str_split(lag, " ")[[1]][1] %>% as.integer())
  }
  gdf$start_date <- rep(start_date,dim(gdf)[1])
  gdf
}
max_date <- as.Date("2018-08-24")
xf <- framework %>% 
  left_join(preview, by = "ticker") %>% 
  group_by(lag) %>%
  do(convert_lag(.,max_date)) %>%
  subset(date >= start_date & date <= max_date) %>%
  arrange(ticker,lag,date) %>%
  ungroup() %>%
  group_by(ticker,lag) %>%
  summarise(close_values = list(list("close" = close, "date"= date)),
            close_hist = list(close),
            close_dates = list(date))%>% 
  ungroup()
#mutate(close_values = merge_columns(close_hist,close_dates))%>% 

list(1,2,3) %>% setNames(list("a","b","c"))
xf
merge_columns <- function(col1,col2){
  col1 <- col1[[1]]
  col2 <- col2[[1]]
  names(col2) <- col2 %>% unlist() %>% as.character()
  list(col1)
}
list("a","b","c") %>% unlist() %>% as.character()
xf$close_values[1][[1]]
xf$close_values[1]$date

xf
```

```{r}
build_sparkline <- function(nested_values){
  
  if (pluck(nested_values, 1,"close")[1] >= tail(pluck(nested_values, 1,"close"),1)){
    color = "red"
    fillColor = "#ff020282"
  }else{
    color = "#0ddd0d" #green"
    fillColor = "#193b05c4"
  }
  
  spk_composite(sparkline(pluck(nested_values, 1,"close"),
                          height = "50px",
                          width = "150",
                          fillColor = fillColor,
                          type = "line",
                          lineColor = color,
                          lineWidth = 2,
                          chartRangeMin = min(pluck(nested_values, 1,"close")),
                          chartRangeMax = max(pluck(nested_values, 1,"close"))
                          ),
                sparkline(pluck(nested_values, 1,"date"),
                          type="bar",
                          fillColor = FALSE,
                          lineWidth = 1,
                          lineColor ='black'
                )
  )
}

xf$close_values[1]
build_sparkline(xf$close_values[1])
```



```{r}

stock_theme <- reactableTheme(backgroundColor = "black",
                              color = "white"
                              #style = 'font-family: "Work Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;"'
)



sdf <- SharedData$new(xf)
div(style = 'font-family: "Work Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;',
    filter_select("ticker", "Ticker", sdf, ~ticker),
    filter_select("lag", "Time Period", sdf, ~lag,multiple = FALSE),
    reactable(sdf,
              theme = stock_theme,
              columns = list(
                ticker = colDef(
                  name = "Company",
                  width = 200,
                  cell = function(value){
                    list(p(value,style = "font-weight: bold;"),
                         p(purrr::pluck(stock_names,value),style = "color:#a8a8a8;")
                         
                    )
                    
                  }
                ),
                close_hist = colDef(
                  name = "Closing Value",
                  cell = function(values) {
                    if (values[1] >= tail(values,1)){
                      color = "red"
                      fillColor = "#ff020282"
                    }else{
                      color = "#0ddd0d" #green"
                      fillColor = "#193b05c4"
                    }
                    
                    sparkline(values,
                              height = "50px",
                              width = "150",
                              fillColor = fillColor,
                              
                              type = "line",
                              lineColor = color,
                              lineWidth = 2,
                              chartRangeMin = min(values),
                              chartRangeMax = max(values))
                  }
                ),
                
                lag = colDef(show = FALSE),
                #close_values = colDef(show = FALSE),
                close_dates = colDef(show = FALSE)
              ))
)


```


```{r}
sl1 <- sparkline(
  c(5,4,5,-2,0,3),
  type='bar',
  barColor="#aaf",
  chartRangeMin=-5,
  chartRangeMax=10,
  # set an id that will make it easier to refer
  #  in the next sparkline
  elementId="sparkline-for-composite"
)

sl2 <- sparkline(
  c(4,1,5,7,9,9,8,7,6,6,4,7,8,4,3,2,2,5,6,7),
  type="line",
  fillColor = FALSE,
  lineColor ='red',
  chartRangeMin = -5,
  chartRangeMax = 10
)



# add sparkline as a composite
spk_composite(sl1, sl2)

# add values and options as a composite
spk_composite(
  sl1,
  values=c(4,1,5,7,9,9,8,7,6,6,4,7,8,4,3,2,2,5,6,7),
  options = list(
    type="line",
    fillColor = FALSE,
    lineColor ='red',
    chartRangeMin = -5,
    chartRangeMax = 10
  )
)

# add combination of sparkline and options as a composite
spk_composite(
  sl1,
  sl2,
  options = list(
    type="box"
  )
)
```

```{r}
sv <- sparkline(
  pluck(xf$close_values, 1,"close"),
  type="line",
  lineWidth = 2,
  fillColor = FALSE,
  lineColor ='red'
)

sv2 <- sparkline(
  pluck(xf$close_values, 1,"date"),
  type="bar",
  fillColor = FALSE,
  lineWidth = 2,
  lineColor ='red'
  
)


```



